# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(c9f8899f-b9e1-4aa6-9181-e86347163014)'
    subscriptionId: 'c9f8899f-b9e1-4aa6-9181-e86347163014'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'mark-new-rg-01'
    location: 'North Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'NewRepo/StorageAccount.json'
    csmParametersFile: 'NewRepo/StorageAccount.Parameters.json'
    deploymentMode: 'Incremental'
    
  displayName: 'Run a multi-line script'
